---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    do_client_id: "{{ lookup('env','DO_CLIENT_ID') }}"
    do_api_key: "{{ lookup('env','DO_API_KEY') }}"
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  tasks:
  - name: Setup DigitalOcean SSH Keys
  - digital_ocean: >
        state=present
        command=ssh
        name=jcio_keys
        ssh_pub_key={{ ssh_pub_key }}
        client_id={{ do_client_id }}
        api_key={{ do_api_key }}
    register: sshkey

  - name: Create Phobos droplet
  - digital_ocean: >
        state=present
        command=droplet
        ssh_key_ids={{ sshkey.ssh.id }}
        name=phobos
        client_id={{ do_client_id }}
        api_key={{ do_api_key }}
        size_id=1
        region_id=2
        image_id=3
        unique_name: yes
        wait_timeout=500
    register: phobos

  - name: Add Phobos to inventory
    add_host:
      name: "{{ phobos.droplet.ip_address }}"
      groups: phobos
    when: phobos.droplet is defined

  - name: Create Deimos droplet
  - digital_ocean: >
        state=present
        command=droplet
        ssh_key_ids={{ sshkey.ssh.id }}
        name=deimos
        client_id={{ do_client_id }}
        api_key={{ do_api_key }}
        size_id=1
        region_id=2
        image_id=3
        unique_name: yes
        wait_timeout=500
    register: deimos

  - name: Add Deimos to inventory
    add_host:
      name: "{{ deimos.droplet.ip_address }}"
      groups: deimos
    when: deimos.droplet is defined

- hosts: phobos
  remote_user: root

  tasks:
    - name: Wait for SSH
      local_action: "wait_for port=22 host={{ inventory_hostname }}"

    - name: Install docker
      apt: name=docker.io state=latest update_cache=yes

- hosts: deimos
  remote_user: root

  tasks:
    - name: Wait for SSH
      local_action: "wait_for port=22 host={{ inventory_hostname }}"

    - name: Install docker
      apt: name=docker.io state=latest update_cache=yes
